name: deploy
env:
  # Use the same ssh-agent socket value across all jobs
  # Useful when a GH action is using SSH behind-the-scenes
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME}}
  KEY: ${{ secrets.WEBHOST_SSH_SHOPWARE_PRIVATE_KEY }}
  PASSPHRASE: ${{ secrets.WEBHOST_SSH_PASSPHRASE }}
  REPO_KEY: ${{ secrets.PRIVATE_REPO_KEY }}
  CODESPACE_KEY: ${{ secrets.CODESPACE_PRIVATE_KEY }} 
  REPO_PASSPHRASE: ${{ secrets.REPO_PASSPHRASE }} 
  ID_ED25519_PRIVATE_KEY: ${{ secrets.ID_ED25519_PRIVATE_KEY }}
  FORMATTED_KEY: ${{ secrets.FORMATTED_KEY }}


on:
 push:
  branches: 
    - features/use_flex_deployer

# It is important to specify "concurrency" for the workflow,
# to prevent concurrency between different deploys.
concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      - name: Deploy
        uses: deployphp/action@master
        with:
          private-key: $FORMATTED_KEY
          dep: --file=testIt.php deploy
          deployer-binary: "vendor/deployer/deployer/dep"
          verbosity: -vvv
          skip-ssh-setup: false    